-- NeetCode roadmap seed (450+) with list flags: blind75, neetcode150, neetcode250
insert into problems (id, slug, title, difficulty, category, blind75, neetcode150, neetcode250) values
  (217, 'contains-duplicate', 'Contains Duplicate', 'Easy', 'Arrays & Hashing', true, true, true),
  (242, 'valid-anagram', 'Valid Anagram', 'Easy', 'Arrays & Hashing', true, true, true),
  (1929, 'concatenation-of-array', 'Concatenation of Array', 'Easy', 'Arrays & Hashing', false, false, true),
  (1, 'two-sum', 'Two Sum', 'Easy', 'Arrays & Hashing', true, true, true),
  (14, 'longest-common-prefix', 'Longest Common Prefix', 'Easy', 'Arrays & Hashing', false, false, true),
  (49, 'group-anagrams', 'Group Anagrams', 'Medium', 'Arrays & Hashing', true, true, true),
  (27, 'remove-element', 'Remove Element', 'Easy', 'Arrays & Hashing', false, false, true),
  (169, 'majority-element', 'Majority Element', 'Easy', 'Arrays & Hashing', false, false, true),
  (705, 'design-hashset', 'Design HashSet', 'Easy', 'Arrays & Hashing', false, false, true),
  (706, 'design-hashmap', 'Design HashMap', 'Easy', 'Arrays & Hashing', false, false, true),
  (912, 'sort-an-array', 'Sort an Array', 'Medium', 'Arrays & Hashing', false, false, true),
  (347, 'top-k-frequent-elements', 'Top K Frequent Elements', 'Medium', 'Arrays & Hashing', true, true, true),
  (238, 'product-of-array-except-self', 'Product of Array Except Self', 'Medium', 'Arrays & Hashing', true, true, true),
  (36, 'valid-sudoku', 'Valid Sudoku', 'Medium', 'Arrays & Hashing', false, true, true),
  (271, 'encode-and-decode-strings', 'Encode and Decode Strings', 'Medium', 'Arrays & Hashing', true, true, true),
  (128, 'longest-consecutive-sequence', 'Longest Consecutive Sequence', 'Medium', 'Arrays & Hashing', true, true, true),
  (75, 'sort-colors', 'Sort Colors', 'Medium', 'Arrays & Hashing', false, false, true),
  (122, 'best-time-to-buy-and-sell-stock-ii', 'Best Time to Buy And Sell Stock II', 'Medium', 'Arrays & Hashing', false, false, true),
  (560, 'subarray-sum-equals-k', 'Subarray Sum Equals K', 'Medium', 'Arrays & Hashing', false, false, true),
  (304, 'range-sum-query-2d-immutable', 'Range Sum Query 2D Immutable', 'Medium', 'Arrays & Hashing', false, false, true),
  (41, 'first-missing-positive', 'First Missing Positive', 'Hard', 'Arrays & Hashing', false, false, true),
  (125, 'valid-palindrome', 'Valid Palindrome', 'Easy', 'Two Pointers', true, true, true),
  (680, 'valid-palindrome-ii', 'Valid Palindrome II', 'Easy', 'Two Pointers', false, false, true),
  (1768, 'merge-strings-alternately', 'Merge Strings Alternately', 'Easy', 'Two Pointers', false, false, true),
  (344, 'reverse-string', 'Reverse String', 'Easy', 'Two Pointers', false, false, true),
  (88, 'merge-sorted-array', 'Merge Sorted Array', 'Easy', 'Two Pointers', false, false, true),
  (26, 'remove-duplicates-from-sorted-array', 'Remove Duplicates From Sorted Array', 'Easy', 'Two Pointers', false, false, true),
  (167, 'two-sum-ii-input-array-is-sorted', 'Two Sum II Input Array Is Sorted', 'Medium', 'Two Pointers', false, true, true),
  (15, '3sum', '3Sum', 'Medium', 'Two Pointers', true, true, true),
  (18, '4sum', '4Sum', 'Medium', 'Two Pointers', false, false, true),
  (11, 'container-with-most-water', 'Container With Most Water', 'Medium', 'Two Pointers', true, true, true),
  (189, 'rotate-array', 'Rotate Array', 'Medium', 'Two Pointers', false, false, true),
  (881, 'boats-to-save-people', 'Boats to Save People', 'Medium', 'Two Pointers', false, false, true),
  (42, 'trapping-rain-water', 'Trapping Rain Water', 'Hard', 'Two Pointers', false, true, true),
  (121, 'best-time-to-buy-and-sell-stock', 'Best Time to Buy And Sell Stock', 'Easy', 'Sliding Window', true, true, true),
  (219, 'contains-duplicate-ii', 'Contains Duplicate II', 'Easy', 'Sliding Window', false, false, true),
  (3, 'longest-substring-without-repeating-characters', 'Longest Substring Without Repeating Characters', 'Medium', 'Sliding Window', true, true, true),
  (424, 'longest-repeating-character-replacement', 'Longest Repeating Character Replacement', 'Medium', 'Sliding Window', true, true, true),
  (567, 'permutation-in-string', 'Permutation In String', 'Medium', 'Sliding Window', false, true, true),
  (209, 'minimum-size-subarray-sum', 'Minimum Size Subarray Sum', 'Medium', 'Sliding Window', false, false, true),
  (658, 'find-k-closest-elements', 'Find K Closest Elements', 'Medium', 'Sliding Window', false, false, true),
  (76, 'minimum-window-substring', 'Minimum Window Substring', 'Hard', 'Sliding Window', true, true, true),
  (239, 'sliding-window-maximum', 'Sliding Window Maximum', 'Hard', 'Sliding Window', false, true, true),
  (20, 'valid-parentheses', 'Valid Parentheses', 'Easy', 'Stack', true, true, true),
  (682, 'baseball-game', 'Baseball Game', 'Easy', 'Stack', false, false, true),
  (225, 'implement-stack-using-queues', 'Implement Stack Using Queues', 'Easy', 'Stack', false, false, true),
  (155, 'min-stack', 'Min Stack', 'Medium', 'Stack', false, true, true),
  (150, 'evaluate-reverse-polish-notation', 'Evaluate Reverse Polish Notation', 'Medium', 'Stack', false, true, true),
  (22, 'generate-parentheses', 'Generate Parentheses', 'Medium', 'Stack', false, true, true),
  (735, 'asteroid-collision', 'Asteroid Collision', 'Medium', 'Stack', false, false, true),
  (739, 'daily-temperatures', 'Daily Temperatures', 'Medium', 'Stack', false, true, true),
  (901, 'online-stock-span', 'Online Stock Span', 'Medium', 'Stack', false, false, true),
  (853, 'car-fleet', 'Car Fleet', 'Medium', 'Stack', false, true, true),
  (71, 'simplify-path', 'Simplify Path', 'Medium', 'Stack', false, false, true),
  (394, 'decode-string', 'Decode String', 'Medium', 'Stack', false, false, true),
  (895, 'maximum-frequency-stack', 'Maximum Frequency Stack', 'Hard', 'Stack', false, false, true),
  (84, 'largest-rectangle-in-histogram', 'Largest Rectangle In Histogram', 'Hard', 'Stack', false, true, true),
  (704, 'binary-search', 'Binary Search', 'Easy', 'Binary Search', false, true, true),
  (35, 'search-insert-position', 'Search Insert Position', 'Easy', 'Binary Search', false, false, true),
  (374, 'guess-number-higher-or-lower', 'Guess Number Higher Or Lower', 'Easy', 'Binary Search', false, false, true),
  (69, 'sqrtx', 'Sqrt(x) ', 'Easy', 'Binary Search', false, false, true),
  (1011, 'capacity-to-ship-packages-within-d-days', 'Capacity to Ship Packages Within D Days', 'Medium', 'Binary Search', false, false, true),
  (74, 'search-a-2d-matrix', 'Search a 2D Matrix', 'Medium', 'Binary Search', false, true, true),
  (875, 'koko-eating-bananas', 'Koko Eating Bananas', 'Medium', 'Binary Search', false, true, true),
  (153, 'find-minimum-in-rotated-sorted-array', 'Find Minimum In Rotated Sorted Array', 'Medium', 'Binary Search', true, true, true),
  (33, 'search-in-rotated-sorted-array', 'Search In Rotated Sorted Array', 'Medium', 'Binary Search', true, true, true),
  (81, 'search-in-rotated-sorted-array-ii', 'Search In Rotated Sorted Array II', 'Medium', 'Binary Search', false, false, true),
  (981, 'time-based-key-value-store', 'Time Based Key Value Store', 'Medium', 'Binary Search', false, true, true),
  (410, 'split-array-largest-sum', 'Split Array Largest Sum', 'Hard', 'Binary Search', false, false, true),
  (4, 'median-of-two-sorted-arrays', 'Median of Two Sorted Arrays', 'Hard', 'Binary Search', false, true, true),
  (206, 'reverse-linked-list', 'Reverse Linked List', 'Easy', 'Linked List', true, true, true),
  (21, 'merge-two-sorted-lists', 'Merge Two Sorted Lists', 'Easy', 'Linked List', true, true, true),
  (143, 'reorder-list', 'Reorder List', 'Medium', 'Linked List', true, true, true),
  (19, 'remove-nth-node-from-end-of-list', 'Remove Nth Node From End of List', 'Medium', 'Linked List', true, true, true),
  (460, 'lfu-cache', 'LFU Cache', 'Hard', 'Linked List', false, false, true),
  (138, 'copy-list-with-random-pointer', 'Copy List With Random Pointer', 'Medium', 'Linked List', false, true, true),
  (2, 'add-two-numbers', 'Add Two Numbers', 'Medium', 'Linked List', false, true, true),
  (141, 'linked-list-cycle', 'Linked List Cycle', 'Easy', 'Linked List', true, true, true),
  (287, 'find-the-duplicate-number', 'Find The Duplicate Number', 'Medium', 'Linked List', false, true, true),
  (92, 'reverse-linked-list-ii', 'Reverse Linked List II', 'Medium', 'Linked List', false, false, true),
  (622, 'design-circular-queue', 'Design Circular Queue', 'Medium', 'Linked List', false, false, true),
  (146, 'lru-cache', 'LRU Cache', 'Medium', 'Linked List', false, true, true),
  (23, 'merge-k-sorted-lists', 'Merge K Sorted Lists', 'Hard', 'Linked List', true, true, true),
  (25, 'reverse-nodes-in-k-group', 'Reverse Nodes In K Group', 'Hard', 'Linked List', false, true, true),
  (94, 'binary-tree-inorder-traversal', 'Binary Tree Inorder Traversal', 'Easy', 'Trees', false, false, true),
  (144, 'binary-tree-preorder-traversal', 'Binary Tree Preorder Traversal', 'Easy', 'Trees', false, false, true),
  (145, 'binary-tree-postorder-traversal', 'Binary Tree Postorder Traversal', 'Easy', 'Trees', false, false, true),
  (226, 'invert-binary-tree', 'Invert Binary Tree', 'Easy', 'Trees', true, true, true),
  (104, 'maximum-depth-of-binary-tree', 'Maximum Depth of Binary Tree', 'Easy', 'Trees', true, true, true),
  (543, 'diameter-of-binary-tree', 'Diameter of Binary Tree', 'Easy', 'Trees', false, true, true),
  (110, 'balanced-binary-tree', 'Balanced Binary Tree', 'Easy', 'Trees', false, true, true),
  (100, 'same-tree', 'Same Tree', 'Easy', 'Trees', true, true, true),
  (572, 'subtree-of-another-tree', 'Subtree of Another Tree', 'Easy', 'Trees', true, true, true),
  (235, 'lowest-common-ancestor-of-a-binary-search-tree', 'Lowest Common Ancestor of a Binary Search Tree', 'Medium', 'Trees', true, true, true),
  (701, 'insert-into-a-binary-search-tree', 'Insert into a Binary Search Tree', 'Medium', 'Trees', false, false, true),
  (450, 'delete-node-in-a-bst', 'Delete Node in a BST', 'Medium', 'Trees', false, false, true),
  (102, 'binary-tree-level-order-traversal', 'Binary Tree Level Order Traversal', 'Medium', 'Trees', true, true, true),
  (199, 'binary-tree-right-side-view', 'Binary Tree Right Side View', 'Medium', 'Trees', false, true, true),
  (427, 'construct-quad-tree', 'Construct Quad Tree', 'Medium', 'Trees', false, false, true),
  (1448, 'count-good-nodes-in-binary-tree', 'Count Good Nodes In Binary Tree', 'Medium', 'Trees', false, true, true),
  (98, 'validate-binary-search-tree', 'Validate Binary Search Tree', 'Medium', 'Trees', true, true, true),
  (230, 'kth-smallest-element-in-a-bst', 'Kth Smallest Element In a Bst', 'Medium', 'Trees', true, true, true),
  (105, 'construct-binary-tree-from-preorder-and-inorder-traversal', 'Construct Binary Tree From Preorder And Inorder Traversal', 'Medium', 'Trees', true, true, true),
  (337, 'house-robber-iii', 'House Robber III', 'Medium', 'Trees', false, false, true),
  (124, 'binary-tree-maximum-path-sum', 'Binary Tree Maximum Path Sum', 'Hard', 'Trees', true, true, true),
  (297, 'serialize-and-deserialize-binary-tree', 'Serialize And Deserialize Binary Tree', 'Hard', 'Trees', true, true, true),
  (208, 'implement-trie-prefix-tree', 'Implement Trie Prefix Tree', 'Medium', 'Tries', true, true, true),
  (211, 'design-add-and-search-words-data-structure', 'Design Add And Search Words Data Structure', 'Medium', 'Tries', true, true, true),
  (2707, 'extra-characters-in-a-string', 'Extra Characters in a String', 'Medium', 'Tries', false, false, true),
  (212, 'word-search-ii', 'Word Search II', 'Hard', 'Tries', true, true, true),
  (703, 'kth-largest-element-in-a-stream', 'Kth Largest Element In a Stream', 'Easy', 'Heap / Priority Queue', false, true, true),
  (1046, 'last-stone-weight', 'Last Stone Weight', 'Easy', 'Heap / Priority Queue', false, true, true),
  (973, 'k-closest-points-to-origin', 'K Closest Points to Origin', 'Medium', 'Heap / Priority Queue', false, true, true),
  (215, 'kth-largest-element-in-an-array', 'Kth Largest Element In An Array', 'Medium', 'Heap / Priority Queue', false, true, true),
  (621, 'task-scheduler', 'Task Scheduler', 'Medium', 'Heap / Priority Queue', false, true, true),
  (355, 'design-twitter', 'Design Twitter', 'Medium', 'Heap / Priority Queue', false, true, true),
  (1834, 'single-threaded-cpu', 'Single Threaded Cpu', 'Medium', 'Heap / Priority Queue', false, false, true),
  (767, 'reorganize-string', 'Reorganize String', 'Medium', 'Heap / Priority Queue', false, false, true),
  (1405, 'longest-happy-string', 'Longest Happy String', 'Medium', 'Heap / Priority Queue', false, false, true),
  (1094, 'car-pooling', 'Car Pooling', 'Medium', 'Heap / Priority Queue', false, false, true),
  (295, 'find-median-from-data-stream', 'Find Median From Data Stream', 'Hard', 'Heap / Priority Queue', true, true, true),
  (502, 'ipo', 'IPO', 'Hard', 'Heap / Priority Queue', false, false, true),
  (78, 'subsets', 'Subsets', 'Medium', 'Backtracking', false, true, true),
  (39, 'combination-sum', 'Combination Sum', 'Medium', 'Backtracking', true, true, true),
  (77, 'combinations', 'Combinations', 'Medium', 'Backtracking', false, false, true),
  (46, 'permutations', 'Permutations', 'Medium', 'Backtracking', false, true, true),
  (90, 'subsets-ii', 'Subsets II', 'Medium', 'Backtracking', false, true, true),
  (40, 'combination-sum-ii', 'Combination Sum II', 'Medium', 'Backtracking', false, true, true),
  (47, 'permutations-ii', 'Permutations II', 'Medium', 'Backtracking', false, false, true),
  (79, 'word-search', 'Word Search', 'Medium', 'Backtracking', true, true, true),
  (131, 'palindrome-partitioning', 'Palindrome Partitioning', 'Medium', 'Backtracking', false, true, true),
  (17, 'letter-combinations-of-a-phone-number', 'Letter Combinations of a Phone Number', 'Medium', 'Backtracking', false, true, true),
  (473, 'matchsticks-to-square', 'Matchsticks to Square', 'Medium', 'Backtracking', false, false, true),
  (698, 'partition-to-k-equal-sum-subsets', 'Partition to K Equal Sum Subsets', 'Medium', 'Backtracking', false, false, true),
  (51, 'n-queens', 'N Queens', 'Hard', 'Backtracking', false, true, true),
  (52, 'n-queens-ii', 'N Queens II', 'Hard', 'Backtracking', false, false, true),
  (463, 'island-perimeter', 'Island Perimeter', 'Easy', 'Graphs', false, false, true),
  (953, 'verifying-an-alien-dictionary', 'Verifying An Alien Dictionary', 'Easy', 'Graphs', false, false, true),
  (200, 'number-of-islands', 'Number of Islands', 'Medium', 'Graphs', true, true, true),
  (133, 'clone-graph', 'Clone Graph', 'Medium', 'Graphs', true, true, true),
  (695, 'max-area-of-island', 'Max Area of Island', 'Medium', 'Graphs', false, true, true),
  (417, 'pacific-atlantic-water-flow', 'Pacific Atlantic Water Flow', 'Medium', 'Graphs', true, true, true),
  (130, 'surrounded-regions', 'Surrounded Regions', 'Medium', 'Graphs', false, true, true),
  (994, 'rotting-oranges', 'Rotting Oranges', 'Medium', 'Graphs', false, true, true),
  (286, 'walls-and-gates', 'Walls And Gates', 'Medium', 'Graphs', false, true, true),
  (752, 'open-the-lock', 'Open The Lock', 'Medium', 'Graphs', false, false, true),
  (207, 'course-schedule', 'Course Schedule', 'Medium', 'Graphs', true, true, true),
  (210, 'course-schedule-ii', 'Course Schedule II', 'Medium', 'Graphs', false, true, true),
  (1462, 'course-schedule-iv', 'Course Schedule IV', 'Medium', 'Graphs', false, false, true),
  (684, 'redundant-connection', 'Redundant Connection', 'Medium', 'Graphs', false, true, true),
  (323, 'number-of-connected-components-in-an-undirected-graph', 'Number of Connected Components In An Undirected Graph', 'Medium', 'Graphs', true, true, true),
  (261, 'graph-valid-tree', 'Graph Valid Tree', 'Medium', 'Graphs', true, true, true),
  (721, 'accounts-merge', 'Accounts Merge', 'Medium', 'Graphs', false, false, true),
  (399, 'evaluate-division', 'Evaluate Division', 'Medium', 'Graphs', false, false, true),
  (127, 'word-ladder', 'Word Ladder', 'Hard', 'Graphs', false, true, true),
  (1631, 'path-with-minimum-effort', 'Path with Minimum Effort', 'Medium', 'Advanced Graphs', false, false, true),
  (332, 'reconstruct-itinerary', 'Reconstruct Itinerary', 'Hard', 'Advanced Graphs', false, true, true),
  (1584, 'min-cost-to-connect-all-points', 'Min Cost to Connect All Points', 'Medium', 'Advanced Graphs', false, true, true),
  (743, 'network-delay-time', 'Network Delay Time', 'Medium', 'Advanced Graphs', false, true, true),
  (778, 'swim-in-rising-water', 'Swim In Rising Water', 'Hard', 'Advanced Graphs', false, true, true),
  (269, 'alien-dictionary', 'Alien Dictionary', 'Hard', 'Advanced Graphs', true, true, true),
  (787, 'cheapest-flights-within-k-stops', 'Cheapest Flights Within K Stops', 'Medium', 'Advanced Graphs', false, true, true),
  (1489, 'find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree', 'Find Critical and Pseudo Critical Edges in Minimum Spanning Tree', 'Hard', 'Advanced Graphs', false, false, true),
  (70, 'climbing-stairs', 'Climbing Stairs', 'Easy', '1-D Dynamic Programming', true, true, true),
  (746, 'min-cost-climbing-stairs', 'Min Cost Climbing Stairs', 'Easy', '1-D Dynamic Programming', false, true, true),
  (198, 'house-robber', 'House Robber', 'Medium', '1-D Dynamic Programming', true, true, true),
  (213, 'house-robber-ii', 'House Robber II', 'Medium', '1-D Dynamic Programming', true, true, true),
  (5, 'longest-palindromic-substring', 'Longest Palindromic Substring', 'Medium', '1-D Dynamic Programming', true, true, true),
  (647, 'palindromic-substrings', 'Palindromic Substrings', 'Medium', '1-D Dynamic Programming', true, true, true),
  (91, 'decode-ways', 'Decode Ways', 'Medium', '1-D Dynamic Programming', true, true, true),
  (322, 'coin-change', 'Coin Change', 'Medium', '1-D Dynamic Programming', true, true, true),
  (152, 'maximum-product-subarray', 'Maximum Product Subarray', 'Medium', '1-D Dynamic Programming', true, true, true),
  (139, 'word-break', 'Word Break', 'Medium', '1-D Dynamic Programming', true, true, true),
  (300, 'longest-increasing-subsequence', 'Longest Increasing Subsequence', 'Medium', '1-D Dynamic Programming', true, true, true),
  (416, 'partition-equal-subset-sum', 'Partition Equal Subset Sum', 'Medium', '1-D Dynamic Programming', false, true, true),
  (377, 'combination-sum-iv', 'Combination Sum IV', 'Medium', '1-D Dynamic Programming', false, false, true),
  (279, 'perfect-squares', 'Perfect Squares', 'Medium', '1-D Dynamic Programming', false, false, true),
  (343, 'integer-break', 'Integer Break', 'Medium', '1-D Dynamic Programming', false, false, true),
  (1137, 'n-th-tribonacci-number', 'N-th Tribonacci Number', 'Easy', '1-D Dynamic Programming', false, false, true),
  (1406, 'stone-game-iii', 'Stone Game III', 'Hard', '1-D Dynamic Programming', false, false, true),
  (62, 'unique-paths', 'Unique Paths', 'Medium', '2-D Dynamic Programming', true, true, true),
  (63, 'unique-paths-ii', 'Unique Paths II', 'Medium', '2-D Dynamic Programming', false, false, true),
  (1143, 'longest-common-subsequence', 'Longest Common Subsequence', 'Medium', '2-D Dynamic Programming', true, true, true),
  (1049, 'last-stone-weight-ii', 'Last Stone Weight II', 'Medium', '2-D Dynamic Programming', false, false, true),
  (309, 'best-time-to-buy-and-sell-stock-with-cooldown', 'Best Time to Buy And Sell Stock With Cooldown', 'Medium', '2-D Dynamic Programming', false, true, true),
  (518, 'coin-change-ii', 'Coin Change II', 'Medium', '2-D Dynamic Programming', false, true, true),
  (494, 'target-sum', 'Target Sum', 'Medium', '2-D Dynamic Programming', false, true, true),
  (97, 'interleaving-string', 'Interleaving String', 'Medium', '2-D Dynamic Programming', false, true, true),
  (877, 'stone-game', 'Stone Game', 'Medium', '2-D Dynamic Programming', false, false, true),
  (64, 'minimum-path-sum', 'Minimum Path Sum', 'Medium', '2-D Dynamic Programming', false, false, true),
  (329, 'longest-increasing-path-in-a-matrix', 'Longest Increasing Path In a Matrix', 'Hard', '2-D Dynamic Programming', false, true, true),
  (115, 'distinct-subsequences', 'Distinct Subsequences', 'Hard', '2-D Dynamic Programming', false, true, true),
  (72, 'edit-distance', 'Edit Distance', 'Medium', '2-D Dynamic Programming', false, true, true),
  (312, 'burst-balloons', 'Burst Balloons', 'Hard', '2-D Dynamic Programming', false, true, true),
  (10, 'regular-expression-matching', 'Regular Expression Matching', 'Hard', '2-D Dynamic Programming', false, true, true),
  (1140, 'stone-game-ii', 'Stone Game II', 'Medium', '2-D Dynamic Programming', false, false, true),
  (53, 'maximum-subarray', 'Maximum Subarray', 'Medium', 'Greedy', true, true, true),
  (918, 'maximum-sum-circular-subarray', 'Maximum Sum Circular Subarray', 'Medium', 'Greedy', false, false, true),
  (978, 'longest-turbulent-subarray', 'Longest Turbulent Subarray', 'Medium', 'Greedy', false, false, true),
  (55, 'jump-game', 'Jump Game', 'Medium', 'Greedy', true, true, true),
  (45, 'jump-game-ii', 'Jump Game II', 'Medium', 'Greedy', false, true, true),
  (1871, 'jump-game-vii', 'Jump Game VII', 'Medium', 'Greedy', false, false, true),
  (134, 'gas-station', 'Gas Station', 'Medium', 'Greedy', false, true, true),
  (846, 'hand-of-straights', 'Hand of Straights', 'Medium', 'Greedy', false, true, true),
  (649, 'dota2-senate', 'Dota2 Senate', 'Medium', 'Greedy', false, false, true),
  (1899, 'merge-triplets-to-form-target-triplet', 'Merge Triplets to Form Target Triplet', 'Medium', 'Greedy', false, true, true),
  (763, 'partition-labels', 'Partition Labels', 'Medium', 'Greedy', false, true, true),
  (678, 'valid-parenthesis-string', 'Valid Parenthesis String', 'Medium', 'Greedy', false, true, true),
  (135, 'candy', 'Candy', 'Hard', 'Greedy', false, false, true),
  (57, 'insert-interval', 'Insert Interval', 'Medium', 'Intervals', true, true, true),
  (56, 'merge-intervals', 'Merge Intervals', 'Medium', 'Intervals', true, true, true),
  (435, 'non-overlapping-intervals', 'Non Overlapping Intervals', 'Medium', 'Intervals', true, true, true),
  (252, 'meeting-rooms', 'Meeting Rooms', 'Easy', 'Intervals', true, true, true),
  (253, 'meeting-rooms-ii', 'Meeting Rooms II', 'Medium', 'Intervals', true, true, true),
  (1851, 'minimum-interval-to-include-each-query', 'Minimum Interval to Include Each Query', 'Hard', 'Intervals', false, true, true),
  (168, 'excel-sheet-column-title', 'Excel Sheet Column Title', 'Easy', 'Math & Geometry', false, false, true),
  (1071, 'greatest-common-divisor-of-strings', 'Greatest Common Divisor of Strings', 'Easy', 'Math & Geometry', false, false, true),
  (48, 'rotate-image', 'Rotate Image', 'Medium', 'Math & Geometry', true, true, true),
  (54, 'spiral-matrix', 'Spiral Matrix', 'Medium', 'Math & Geometry', true, true, true),
  (73, 'set-matrix-zeroes', 'Set Matrix Zeroes', 'Medium', 'Math & Geometry', true, true, true),
  (202, 'happy-number', 'Happy Number', 'Easy', 'Math & Geometry', false, true, true),
  (66, 'plus-one', 'Plus One', 'Easy', 'Math & Geometry', false, true, true),
  (13, 'roman-to-integer', 'Roman to Integer', 'Easy', 'Math & Geometry', false, false, true),
  (50, 'powx-n', 'Pow(x, n)', 'Medium', 'Math & Geometry', false, true, true),
  (43, 'multiply-strings', 'Multiply Strings', 'Medium', 'Math & Geometry', false, true, true),
  (2013, 'detect-squares', 'Detect Squares', 'Medium', 'Math & Geometry', false, true, true),
  (136, 'single-number', 'Single Number', 'Easy', 'Bit Manipulation', false, true, true),
  (191, 'number-of-1-bits', 'Number of 1 Bits', 'Easy', 'Bit Manipulation', true, true, true),
  (338, 'counting-bits', 'Counting Bits', 'Easy', 'Bit Manipulation', true, true, true),
  (190, 'reverse-bits', 'Reverse Bits', 'Easy', 'Bit Manipulation', true, true, true),
  (268, 'missing-number', 'Missing Number', 'Easy', 'Bit Manipulation', true, true, true),
  (371, 'sum-of-two-integers', 'Sum of Two Integers', 'Medium', 'Bit Manipulation', true, true, true),
  (7, 'reverse-integer', 'Reverse Integer', 'Medium', 'Bit Manipulation', false, true, true),
  (67, 'add-binary', 'Add Binary', 'Easy', 'Bit Manipulation', false, false, true),
  (229, 'majority-element-ii', 'Majority Element II', 'Medium', 'Arrays & Hashing', false, false, true),
  (232, 'implement-queue-using-stacks', 'Implement Queue using Stacks', 'Easy', 'Stack', false, false, true),
  (1095, 'find-in-mountain-array', 'Find in Mountain Array', 'Hard', 'Binary Search', false, false, true),
  (1325, 'delete-leaves-with-a-given-value', 'Delete Leaves With a Given Value', 'Medium', 'Trees', false, false, true),
  (1863, 'sum-of-all-subset-xor-totals', 'Sum of All Subset XOR Totals', 'Easy', 'Backtracking', false, false, true),
  (140, 'word-break-ii', 'Word Break II', 'Hard', 'Backtracking', false, false, true),
  (997, 'find-the-town-judge', 'Find the Town Judge', 'Easy', 'Graphs', false, false, true),
  (310, 'minimum-height-trees', 'Minimum Height Trees', 'Medium', 'Graphs', false, false, true),
  (2392, 'build-a-matrix-with-conditions', 'Build a Matrix With Conditions', 'Hard', 'Advanced Graphs', false, false, true),
  (2709, 'greatest-common-divisor-traversal', 'Greatest Common Divisor Traversal', 'Hard', 'Advanced Graphs', false, false, true),
  (860, 'lemonade-change', 'Lemonade Change', 'Easy', 'Greedy', false, false, true),
  (2402, 'meeting-rooms-iii', 'Meeting Rooms III', 'Hard', 'Intervals', false, false, true),
  (2807, 'insert-greatest-common-divisors-in-linked-list', 'Insert Greatest Common Divisors in Linked List', 'Medium', 'Math & Geometry', false, false, true),
  (867, 'transpose-matrix', 'Transpose Matrix', 'Easy', 'Math & Geometry', false, false, true),
  (201, 'bitwise-and-of-numbers-range', 'Bitwise AND of Numbers Range', 'Medium', 'Bit Manipulation', false, false, true),
  (3133, 'minimum-array-end', 'Minimum Array End', 'Medium', 'Bit Manipulation', false, false, true)
on conflict (id) do update set
  slug=excluded.slug, title=excluded.title, difficulty=excluded.difficulty,
  category=excluded.category, blind75=excluded.blind75, neetcode150=excluded.neetcode150, neetcode250=excluded.neetcode250;
