-- NeetCode roadmap seed (450+) with list flags: blind75, neetcode150, neetcode250
insert into problems (id, slug, title, difficulty, category, blind75, neetcode150, neetcode250) values
  (217, 'contains-duplicate', 'Contains Duplicate', 'Easy', 'Arrays & Hashing', true, true, true),
  (242, 'valid-anagram', 'Valid Anagram', 'Easy', 'Arrays & Hashing', true, true, true),
  (1929, 'concatenation-of-array', 'Concatenation of Array', 'Easy', 'Arrays & Hashing', false, false, true),
  (1299, 'replace-elements-with-greatest-element-on-right-side', 'Replace Elements With Greatest Element On Right Side', 'Easy', 'Arrays & Hashing', false, false, false),
  (392, 'is-subsequence', 'Is Subsequence', 'Easy', 'Arrays & Hashing', false, false, false),
  (58, 'length-of-last-word', 'Length of Last Word', 'Easy', 'Arrays & Hashing', false, false, false),
  (1, 'two-sum', 'Two Sum', 'Easy', 'Arrays & Hashing', true, true, true),
  (14, 'longest-common-prefix', 'Longest Common Prefix', 'Easy', 'Arrays & Hashing', false, false, true),
  (49, 'group-anagrams', 'Group Anagrams', 'Medium', 'Arrays & Hashing', true, true, true),
  (118, 'pascals-triangle', 'Pascals Triangle', 'Easy', 'Arrays & Hashing', false, false, false),
  (27, 'remove-element', 'Remove Element', 'Easy', 'Arrays & Hashing', false, false, true),
  (929, 'unique-email-addresses', 'Unique Email Addresses', 'Easy', 'Arrays & Hashing', false, false, false),
  (205, 'isomorphic-strings', 'Isomorphic Strings', 'Easy', 'Arrays & Hashing', false, false, false),
  (605, 'can-place-flowers', 'Can Place Flowers', 'Easy', 'Arrays & Hashing', false, false, false),
  (169, 'majority-element', 'Majority Element', 'Easy', 'Arrays & Hashing', false, false, true),
  (496, 'next-greater-element-i', 'Next Greater Element I', 'Easy', 'Arrays & Hashing', false, false, false),
  (724, 'find-pivot-index', 'Find Pivot Index', 'Easy', 'Arrays & Hashing', false, false, false),
  (303, 'range-sum-query-immutable', 'Range Sum Query - Immutable', 'Easy', 'Arrays & Hashing', false, false, false),
  (448, 'find-all-numbers-disappeared-in-an-array', 'Find All Numbers Disappeared in An Array', 'Easy', 'Arrays & Hashing', false, false, false),
  (1189, 'maximum-number-of-balloons', 'Maximum Number of Balloons', 'Easy', 'Arrays & Hashing', false, false, false),
  (290, 'word-pattern', 'Word Pattern', 'Easy', 'Arrays & Hashing', false, false, false),
  (705, 'design-hashset', 'Design HashSet', 'Easy', 'Arrays & Hashing', false, false, true),
  (706, 'design-hashmap', 'Design HashMap', 'Easy', 'Arrays & Hashing', false, false, true),
  (912, 'sort-an-array', 'Sort an Array', 'Medium', 'Arrays & Hashing', false, false, true),
  (347, 'top-k-frequent-elements', 'Top K Frequent Elements', 'Medium', 'Arrays & Hashing', true, true, true),
  (238, 'product-of-array-except-self', 'Product of Array Except Self', 'Medium', 'Arrays & Hashing', true, true, true),
  (36, 'valid-sudoku', 'Valid Sudoku', 'Medium', 'Arrays & Hashing', false, true, true),
  (271, 'encode-and-decode-strings', 'Encode and Decode Strings', 'Medium', 'Arrays & Hashing', true, true, true),
  (128, 'longest-consecutive-sequence', 'Longest Consecutive Sequence', 'Medium', 'Arrays & Hashing', true, true, true),
  (75, 'sort-colors', 'Sort Colors', 'Medium', 'Arrays & Hashing', false, false, true),
  (535, 'encode-and-decode-tinyurl', 'Encode and Decode TinyURL', 'Medium', 'Arrays & Hashing', false, false, false),
  (554, 'brick-wall', 'Brick Wall', 'Medium', 'Arrays & Hashing', false, false, false),
  (122, 'best-time-to-buy-and-sell-stock-ii', 'Best Time to Buy And Sell Stock II', 'Medium', 'Arrays & Hashing', false, false, true),
  (560, 'subarray-sum-equals-k', 'Subarray Sum Equals K', 'Medium', 'Arrays & Hashing', false, false, true),
  (1930, 'unique-length-3-palindromic-subsequences', 'Unique Length 3 Palindromic Subsequences', 'Medium', 'Arrays & Hashing', false, false, false),
  (1963, 'minimum-number-of-swaps-to-make-the-string-balanced', 'Minimum Number of Swaps to Make The String Balanced', 'Medium', 'Arrays & Hashing', false, false, false),
  (2001, 'number-of-pairs-of-interchangeable-rectangles', 'Number of Pairs of Interchangeable Rectangles', 'Medium', 'Arrays & Hashing', false, false, false),
  (2002, 'maximum-product-of-the-length-of-two-palindromic-subsequences', 'Maximum Product of The Length of Two Palindromic Subsequences', 'Medium', 'Arrays & Hashing', false, false, false),
  (2017, 'grid-game', 'Grid Game', 'Medium', 'Arrays & Hashing', false, false, false),
  (438, 'find-all-anagrams-in-a-string', 'Find All Anagrams in a String', 'Medium', 'Arrays & Hashing', false, false, false),
  (28, 'find-the-index-of-the-first-occurrence-in-a-string', 'Find The Index of The First Occurrence in a String', 'Easy', 'Arrays & Hashing', false, false, false),
  (280, 'wiggle-sort', 'Wiggle Sort', 'Medium', 'Arrays & Hashing', false, false, false),
  (179, 'largest-number', 'Largest Number', 'Medium', 'Arrays & Hashing', false, false, false),
  (523, 'continuous-subarray-sum', 'Continuous Subarray Sum', 'Medium', 'Arrays & Hashing', false, false, false),
  (838, 'push-dominoes', 'Push Dominoes', 'Medium', 'Arrays & Hashing', false, false, false),
  (187, 'repeated-dna-sequences', 'Repeated DNA Sequences', 'Medium', 'Arrays & Hashing', false, false, false),
  (380, 'insert-delete-getrandom-o1', 'Insert Delete Get Random O(1)', 'Medium', 'Arrays & Hashing', false, false, false),
  (1461, 'check-if-a-string-contains-all-binary-codes-of-size-k', 'Check if a String Contains all Binary Codes of Size K', 'Medium', 'Arrays & Hashing', false, false, false),
  (304, 'range-sum-query-2d-immutable', 'Range Sum Query 2D Immutable', 'Medium', 'Arrays & Hashing', false, false, true),
  (665, 'non-decreasing-array', 'Non Decreasing Array', 'Medium', 'Arrays & Hashing', false, false, false),
  (41, 'first-missing-positive', 'First Missing Positive', 'Hard', 'Arrays & Hashing', false, false, true),
  (1822, 'sign-of-the-product-of-an-array', 'Sign of An Array', 'Easy', 'Arrays & Hashing', false, false, false),
  (2215, 'find-the-difference-of-two-arrays', 'Find the Difference of Two Arrays', 'Easy', 'Arrays & Hashing', false, false, false),
  (1603, 'design-parking-system', 'Design Parking System', 'Easy', 'Arrays & Hashing', false, false, false),
  (2348, 'number-of-zero-filled-subarrays', 'Number of Zero-Filled Subarrays', 'Medium', 'Arrays & Hashing', false, false, false),
  (2405, 'optimal-partition-of-string', 'Optimal Partition of String', 'Medium', 'Arrays & Hashing', false, false, false),
  (1396, 'design-underground-system', 'Design Underground System', 'Medium', 'Arrays & Hashing', false, false, false),
  (2483, 'minimum-penalty-for-a-shop', 'Minimum Penalty for a Shop', 'Medium', 'Arrays & Hashing', false, false, false),
  (68, 'text-justification', 'Text Justification', 'Hard', 'Arrays & Hashing', false, false, false),
  (2306, 'naming-a-company', 'Naming a Company', 'Hard', 'Arrays & Hashing', false, false, false),
  (125, 'valid-palindrome', 'Valid Palindrome', 'Easy', 'Two Pointers', true, true, true),
  (680, 'valid-palindrome-ii', 'Valid Palindrome II', 'Easy', 'Two Pointers', false, false, true),
  (1984, 'minimum-difference-between-highest-and-lowest-of-k-scores', 'Minimum Difference Between Highest And Lowest of K Scores', 'Easy', 'Two Pointers', false, false, false),
  (1768, 'merge-strings-alternately', 'Merge Strings Alternately', 'Easy', 'Two Pointers', false, false, true),
  (344, 'reverse-string', 'Reverse String', 'Easy', 'Two Pointers', false, false, true),
  (88, 'merge-sorted-array', 'Merge Sorted Array', 'Easy', 'Two Pointers', false, false, true),
  (283, 'move-zeroes', 'Move Zeroes', 'Easy', 'Two Pointers', false, false, false),
  (26, 'remove-duplicates-from-sorted-array', 'Remove Duplicates From Sorted Array', 'Easy', 'Two Pointers', false, false, true),
  (80, 'remove-duplicates-from-sorted-array-ii', 'Remove Duplicates From Sorted Array II', 'Medium', 'Two Pointers', false, false, false),
  (167, 'two-sum-ii-input-array-is-sorted', 'Two Sum II Input Array Is Sorted', 'Medium', 'Two Pointers', false, true, true),
  (15, '3sum', '3Sum', 'Medium', 'Two Pointers', true, true, true),
  (18, '4sum', '4Sum', 'Medium', 'Two Pointers', false, false, true),
  (11, 'container-with-most-water', 'Container With Most Water', 'Medium', 'Two Pointers', true, true, true),
  (1498, 'number-of-subsequences-that-satisfy-the-given-sum-condition', 'Number of Subsequences That Satisfy The Given Sum Condition', 'Medium', 'Two Pointers', false, false, false),
  (189, 'rotate-array', 'Rotate Array', 'Medium', 'Two Pointers', false, false, true),
  (1968, 'array-with-elements-not-equal-to-average-of-neighbors', 'Array With Elements Not Equal to Average of Neighbors', 'Medium', 'Two Pointers', false, false, false),
  (881, 'boats-to-save-people', 'Boats to Save People', 'Medium', 'Two Pointers', false, false, true),
  (42, 'trapping-rain-water', 'Trapping Rain Water', 'Hard', 'Two Pointers', false, true, true),
  (121, 'best-time-to-buy-and-sell-stock', 'Best Time to Buy And Sell Stock', 'Easy', 'Sliding Window', true, true, true),
  (219, 'contains-duplicate-ii', 'Contains Duplicate II', 'Easy', 'Sliding Window', false, false, true),
  (1343, 'number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold', 'Number of Sub Arrays of Size K and Avg Greater than or Equal to Threshold', 'Medium', 'Sliding Window', false, false, false),
  (3, 'longest-substring-without-repeating-characters', 'Longest Substring Without Repeating Characters', 'Medium', 'Sliding Window', true, true, true),
  (424, 'longest-repeating-character-replacement', 'Longest Repeating Character Replacement', 'Medium', 'Sliding Window', true, true, true),
  (567, 'permutation-in-string', 'Permutation In String', 'Medium', 'Sliding Window', false, true, true),
  (1838, 'frequency-of-the-most-frequent-element', 'Frequency of The Most Frequent Element', 'Medium', 'Sliding Window', false, false, false),
  (904, 'fruit-into-baskets', 'Fruits into Basket', 'Medium', 'Sliding Window', false, false, false),
  (1456, 'maximum-number-of-vowels-in-a-substring-of-given-length', 'Maximum Number of Vowels in a Substring of Given Length', 'Medium', 'Sliding Window', false, false, false),
  (1888, 'minimum-number-of-flips-to-make-the-binary-string-alternating', 'Minimum Number of Flips to Make The Binary String Alternating', 'Medium', 'Sliding Window', false, false, false),
  (209, 'minimum-size-subarray-sum', 'Minimum Size Subarray Sum', 'Medium', 'Sliding Window', false, false, true),
  (658, 'find-k-closest-elements', 'Find K Closest Elements', 'Medium', 'Sliding Window', false, false, true),
  (1658, 'minimum-operations-to-reduce-x-to-zero', 'Minimum Operations to Reduce X to Zero', 'Medium', 'Sliding Window', false, false, false),
  (76, 'minimum-window-substring', 'Minimum Window Substring', 'Hard', 'Sliding Window', true, true, true),
  (239, 'sliding-window-maximum', 'Sliding Window Maximum', 'Hard', 'Sliding Window', false, true, true),
  (20, 'valid-parentheses', 'Valid Parentheses', 'Easy', 'Stack', true, true, true),
  (682, 'baseball-game', 'Baseball Game', 'Easy', 'Stack', false, false, true),
  (225, 'implement-stack-using-queues', 'Implement Stack Using Queues', 'Easy', 'Stack', false, false, true),
  (155, 'min-stack', 'Min Stack', 'Medium', 'Stack', false, true, true),
  (150, 'evaluate-reverse-polish-notation', 'Evaluate Reverse Polish Notation', 'Medium', 'Stack', false, true, true),
  (2390, 'removing-stars-from-a-string', 'Removing Stars From a String', 'Medium', 'Stack', false, false, false),
  (946, 'validate-stack-sequences', 'Validate Stack Sequences', 'Medium', 'Stack', false, false, false),
  (22, 'generate-parentheses', 'Generate Parentheses', 'Medium', 'Stack', false, true, true),
  (735, 'asteroid-collision', 'Asteroid Collision', 'Medium', 'Stack', false, false, true),
  (739, 'daily-temperatures', 'Daily Temperatures', 'Medium', 'Stack', false, true, true),
  (901, 'online-stock-span', 'Online Stock Span', 'Medium', 'Stack', false, false, true),
  (853, 'car-fleet', 'Car Fleet', 'Medium', 'Stack', false, true, true),
  (71, 'simplify-path', 'Simplify Path', 'Medium', 'Stack', false, false, true),
  (394, 'decode-string', 'Decode String', 'Medium', 'Stack', false, false, true),
  (402, 'remove-k-digits', 'Remove K Digits', 'Medium', 'Stack', false, false, false),
  (1209, 'remove-all-adjacent-duplicates-in-string-ii', 'Remove All Adjacent Duplicates In String II', 'Medium', 'Stack', false, false, false),
  (456, '132-pattern', '132 Pattern', 'Medium', 'Stack', false, false, false),
  (895, 'maximum-frequency-stack', 'Maximum Frequency Stack', 'Hard', 'Stack', false, false, true),
  (84, 'largest-rectangle-in-histogram', 'Largest Rectangle In Histogram', 'Hard', 'Stack', false, true, true),
  (704, 'binary-search', 'Binary Search', 'Easy', 'Binary Search', false, true, true),
  (35, 'search-insert-position', 'Search Insert Position', 'Easy', 'Binary Search', false, false, true),
  (374, 'guess-number-higher-or-lower', 'Guess Number Higher Or Lower', 'Easy', 'Binary Search', false, false, true),
  (441, 'arranging-coins', 'Arranging Coins', 'Easy', 'Binary Search', false, false, false),
  (977, 'squares-of-a-sorted-array', 'Squares of a Sorted Array', 'Easy', 'Binary Search', false, false, false),
  (367, 'valid-perfect-square', 'Valid Perfect Square', 'Easy', 'Binary Search', false, false, false),
  (69, 'sqrtx', 'Sqrt(x) ', 'Easy', 'Binary Search', false, false, true),
  (540, 'single-element-in-a-sorted-array', 'Single Element in a Sorted Array', 'Medium', 'Binary Search', false, false, false),
  (1011, 'capacity-to-ship-packages-within-d-days', 'Capacity to Ship Packages Within D Days', 'Medium', 'Binary Search', false, false, true),
  (162, 'find-peak-element', 'Find Peak Element', 'Medium', 'Binary Search', false, false, false),
  (2300, 'successful-pairs-of-spells-and-potions', 'Successful Pairs of Spells and Potions', 'Medium', 'Binary Search', false, false, false),
  (74, 'search-a-2d-matrix', 'Search a 2D Matrix', 'Medium', 'Binary Search', false, true, true),
  (875, 'koko-eating-bananas', 'Koko Eating Bananas', 'Medium', 'Binary Search', false, true, true),
  (2616, 'minimize-the-maximum-difference-of-pairs', 'Minimize the Maximum Difference of Pairs', 'Medium', 'Binary Search', false, false, false),
  (153, 'find-minimum-in-rotated-sorted-array', 'Find Minimum In Rotated Sorted Array', 'Medium', 'Binary Search', true, true, true),
  (33, 'search-in-rotated-sorted-array', 'Search In Rotated Sorted Array', 'Medium', 'Binary Search', true, true, true),
  (81, 'search-in-rotated-sorted-array-ii', 'Search In Rotated Sorted Array II', 'Medium', 'Binary Search', false, false, true),
  (981, 'time-based-key-value-store', 'Time Based Key Value Store', 'Medium', 'Binary Search', false, true, true),
  (34, 'find-first-and-last-position-of-element-in-sorted-array', 'Find First And Last Position of Element In Sorted Array', 'Medium', 'Binary Search', false, false, false),
  (1898, 'maximum-number-of-removable-characters', 'Maximum Number of Removable Characters', 'Medium', 'Binary Search', false, false, false),
  (116, 'populating-next-right-pointers-in-each-node', 'Populating Next Right Pointers In Each Node', 'Medium', 'Binary Search', false, false, false),
  (1268, 'search-suggestions-system', 'Search Suggestions System', 'Medium', 'Binary Search', false, false, false),
  (410, 'split-array-largest-sum', 'Split Array Largest Sum', 'Hard', 'Binary Search', false, false, true),
  (4, 'median-of-two-sorted-arrays', 'Median of Two Sorted Arrays', 'Hard', 'Binary Search', false, true, true),
  (206, 'reverse-linked-list', 'Reverse Linked List', 'Easy', 'Linked List', true, true, true),
  (21, 'merge-two-sorted-lists', 'Merge Two Sorted Lists', 'Easy', 'Linked List', true, true, true),
  (234, 'palindrome-linked-list', 'Palindrome Linked List', 'Easy', 'Linked List', false, false, false),
  (203, 'remove-linked-list-elements', 'Remove Linked List Elements', 'Easy', 'Linked List', false, false, false),
  (83, 'remove-duplicates-from-sorted-list', 'Remove Duplicates From Sorted List', 'Easy', 'Linked List', false, false, false),
  (876, 'middle-of-the-linked-list', 'Middle of the Linked List', 'Easy', 'Linked List', false, false, false),
  (160, 'intersection-of-two-linked-lists', 'Intersection of Two Linked Lists', 'Easy', 'Linked List', false, false, false),
  (143, 'reorder-list', 'Reorder List', 'Medium', 'Linked List', true, true, true),
  (2130, 'maximum-twin-sum-of-a-linked-list', 'Maximum Twin Sum Of A Linked List', 'Medium', 'Linked List', false, false, false),
  (19, 'remove-nth-node-from-end-of-list', 'Remove Nth Node From End of List', 'Medium', 'Linked List', true, true, true),
  (1721, 'swapping-nodes-in-a-linked-list', 'Swapping Nodes in a Linked List', 'Medium', 'Linked List', false, false, false),
  (460, 'lfu-cache', 'LFU Cache', 'Hard', 'Linked List', false, false, true),
  (138, 'copy-list-with-random-pointer', 'Copy List With Random Pointer', 'Medium', 'Linked List', false, true, true),
  (707, 'design-linked-list', 'Design Linked List', 'Medium', 'Linked List', false, false, false),
  (1472, 'design-browser-history', 'Design Browser History', 'Medium', 'Linked List', false, false, false),
  (2, 'add-two-numbers', 'Add Two Numbers', 'Medium', 'Linked List', false, true, true),
  (141, 'linked-list-cycle', 'Linked List Cycle', 'Easy', 'Linked List', true, true, true),
  (287, 'find-the-duplicate-number', 'Find The Duplicate Number', 'Medium', 'Linked List', false, true, true),
  (24, 'swap-nodes-in-pairs', 'Swap Nodes In Pairs', 'Medium', 'Linked List', false, false, false),
  (148, 'sort-list', 'Sort List', 'Medium', 'Linked List', false, false, false),
  (86, 'partition-list', 'Partition List', 'Medium', 'Linked List', false, false, false),
  (61, 'rotate-list', 'Rotate List', 'Medium', 'Linked List', false, false, false),
  (92, 'reverse-linked-list-ii', 'Reverse Linked List II', 'Medium', 'Linked List', false, false, true),
  (622, 'design-circular-queue', 'Design Circular Queue', 'Medium', 'Linked List', false, false, true),
  (147, 'insertion-sort-list', 'Insertion Sort List', 'Medium', 'Linked List', false, false, false),
  (725, 'split-linked-list-in-parts', 'Split Linked List in Parts', 'Medium', 'Linked List', false, false, false),
  (146, 'lru-cache', 'LRU Cache', 'Medium', 'Linked List', false, true, true),
  (23, 'merge-k-sorted-lists', 'Merge K Sorted Lists', 'Hard', 'Linked List', true, true, true),
  (25, 'reverse-nodes-in-k-group', 'Reverse Nodes In K Group', 'Hard', 'Linked List', false, true, true),
  (94, 'binary-tree-inorder-traversal', 'Binary Tree Inorder Traversal', 'Easy', 'Trees', false, false, true),
  (144, 'binary-tree-preorder-traversal', 'Binary Tree Preorder Traversal', 'Easy', 'Trees', false, false, true),
  (145, 'binary-tree-postorder-traversal', 'Binary Tree Postorder Traversal', 'Easy', 'Trees', false, false, true),
  (226, 'invert-binary-tree', 'Invert Binary Tree', 'Easy', 'Trees', true, true, true),
  (104, 'maximum-depth-of-binary-tree', 'Maximum Depth of Binary Tree', 'Easy', 'Trees', true, true, true),
  (543, 'diameter-of-binary-tree', 'Diameter of Binary Tree', 'Easy', 'Trees', false, true, true),
  (110, 'balanced-binary-tree', 'Balanced Binary Tree', 'Easy', 'Trees', false, true, true),
  (100, 'same-tree', 'Same Tree', 'Easy', 'Trees', true, true, true),
  (572, 'subtree-of-another-tree', 'Subtree of Another Tree', 'Easy', 'Trees', true, true, true),
  (108, 'convert-sorted-array-to-binary-search-tree', 'Convert Sorted Array to Binary Search Tree', 'Easy', 'Trees', false, false, false),
  (617, 'merge-two-binary-trees', 'Merge Two Binary Trees', 'Easy', 'Trees', false, false, false),
  (112, 'path-sum', 'Path Sum', 'Easy', 'Trees', false, false, false),
  (606, 'construct-string-from-binary-tree', 'Construct String From Binary Tree', 'Easy', 'Trees', false, false, false),
  (235, 'lowest-common-ancestor-of-a-binary-search-tree', 'Lowest Common Ancestor of a Binary Search Tree', 'Medium', 'Trees', true, true, true),
  (701, 'insert-into-a-binary-search-tree', 'Insert into a Binary Search Tree', 'Medium', 'Trees', false, false, true),
  (450, 'delete-node-in-a-bst', 'Delete Node in a BST', 'Medium', 'Trees', false, false, true),
  (102, 'binary-tree-level-order-traversal', 'Binary Tree Level Order Traversal', 'Medium', 'Trees', true, true, true),
  (199, 'binary-tree-right-side-view', 'Binary Tree Right Side View', 'Medium', 'Trees', false, true, true),
  (783, 'minimum-distance-between-bst-nodes', 'Minimum Distance between BST Nodes', 'Easy', 'Trees', false, false, false),
  (101, 'symmetric-tree', 'Symmetric Tree ', 'Easy', 'Trees', false, false, false),
  (1443, 'minimum-time-to-collect-all-apples-in-a-tree', 'Minimum Time to Collect All Apples in a Tree', 'Medium', 'Trees', false, false, false),
  (103, 'binary-tree-zigzag-level-order-traversal', 'Binary Tree Zigzag Level Order Traversal', 'Medium', 'Trees', false, false, false),
  (427, 'construct-quad-tree', 'Construct Quad Tree', 'Medium', 'Trees', false, false, true),
  (652, 'find-duplicate-subtrees', 'Find Duplicate Subtrees', 'Medium', 'Trees', false, false, false),
  (958, 'check-completeness-of-a-binary-tree', 'Check Completeness of a Binary Tree', 'Medium', 'Trees', false, false, false),
  (106, 'construct-binary-tree-from-inorder-and-postorder-traversal', 'Construct Binary Tree from Inorder and Postorder Traversal', 'Medium', 'Trees', false, false, false),
  (662, 'maximum-width-of-binary-tree', 'Maximum Width of Binary Tree ', 'Medium', 'Trees', false, false, false),
  (1376, 'time-needed-to-inform-all-employees', 'Time Needed to Inform All Employees ', 'Medium', 'Trees', false, false, false),
  (1448, 'count-good-nodes-in-binary-tree', 'Count Good Nodes In Binary Tree', 'Medium', 'Trees', false, true, true),
  (98, 'validate-binary-search-tree', 'Validate Binary Search Tree', 'Medium', 'Trees', true, true, true),
  (230, 'kth-smallest-element-in-a-bst', 'Kth Smallest Element In a Bst', 'Medium', 'Trees', true, true, true),
  (105, 'construct-binary-tree-from-preorder-and-inorder-traversal', 'Construct Binary Tree From Preorder And Inorder Traversal', 'Medium', 'Trees', true, true, true),
  (96, 'unique-binary-search-trees', 'Unique Binary Search Trees', 'Medium', 'Trees', false, false, false),
  (95, 'unique-binary-search-trees-ii', 'Unique Binary Search Trees II', 'Medium', 'Trees', false, false, false),
  (129, 'sum-root-to-leaf-numbers', 'Sum Root to Leaf Numbers', 'Medium', 'Trees', false, false, false),
  (337, 'house-robber-iii', 'House Robber III', 'Medium', 'Trees', false, false, true),
  (951, 'flip-equivalent-binary-trees', 'Flip Equivalent Binary Trees', 'Medium', 'Trees', false, false, false),
  (1993, 'operations-on-tree', 'Operations On Tree', 'Medium', 'Trees', false, false, false),
  (894, 'all-possible-full-binary-trees', 'All Possible Full Binary Trees', 'Medium', 'Trees', false, false, false),
  (513, 'find-bottom-left-tree-value', 'Find Bottom Left Tree Value', 'Medium', 'Trees', false, false, false),
  (669, 'trim-a-binary-search-tree', 'Trim a Binary Search Tree', 'Medium', 'Trees', false, false, false),
  (173, 'binary-search-tree-iterator', 'Binary Search Tree Iterator', 'Medium', 'Trees', false, false, false),
  (538, 'convert-bst-to-greater-tree', 'Convert Bst to Greater Tree', 'Medium', 'Trees', false, false, false),
  (124, 'binary-tree-maximum-path-sum', 'Binary Tree Maximum Path Sum', 'Hard', 'Trees', true, true, true),
  (297, 'serialize-and-deserialize-binary-tree', 'Serialize And Deserialize Binary Tree', 'Hard', 'Trees', true, true, true),
  (208, 'implement-trie-prefix-tree', 'Implement Trie Prefix Tree', 'Medium', 'Tries', true, true, true),
  (211, 'design-add-and-search-words-data-structure', 'Design Add And Search Words Data Structure', 'Medium', 'Tries', true, true, true),
  (2707, 'extra-characters-in-a-string', 'Extra Characters in a String', 'Medium', 'Tries', false, false, true),
  (212, 'word-search-ii', 'Word Search II', 'Hard', 'Tries', true, true, true),
  (703, 'kth-largest-element-in-a-stream', 'Kth Largest Element In a Stream', 'Easy', 'Heap / Priority Queue', false, true, true),
  (1046, 'last-stone-weight', 'Last Stone Weight', 'Easy', 'Heap / Priority Queue', false, true, true),
  (973, 'k-closest-points-to-origin', 'K Closest Points to Origin', 'Medium', 'Heap / Priority Queue', false, true, true),
  (215, 'kth-largest-element-in-an-array', 'Kth Largest Element In An Array', 'Medium', 'Heap / Priority Queue', false, true, true),
  (621, 'task-scheduler', 'Task Scheduler', 'Medium', 'Heap / Priority Queue', false, true, true),
  (355, 'design-twitter', 'Design Twitter', 'Medium', 'Heap / Priority Queue', false, true, true),
  (1675, 'minimize-deviation-in-array', 'Minimize Deviation in Array', 'Hard', 'Heap / Priority Queue', false, false, false),
  (2542, 'maximum-subsequence-score', 'Maximum Subsequence Score', 'Medium', 'Heap / Priority Queue', false, false, false),
  (1834, 'single-threaded-cpu', 'Single Threaded Cpu', 'Medium', 'Heap / Priority Queue', false, false, true),
  (1845, 'seat-reservation-manager', 'Seat Reservation Manager', 'Medium', 'Heap / Priority Queue', false, false, false),
  (1882, 'process-tasks-using-servers', 'Process Tasks Using Servers', 'Medium', 'Heap / Priority Queue', false, false, false),
  (1985, 'find-the-kth-largest-integer-in-the-array', 'Find The Kth Largest Integer In The Array', 'Medium', 'Heap / Priority Queue', false, false, false),
  (767, 'reorganize-string', 'Reorganize String', 'Medium', 'Heap / Priority Queue', false, false, true),
  (1405, 'longest-happy-string', 'Longest Happy String', 'Medium', 'Heap / Priority Queue', false, false, true),
  (1094, 'car-pooling', 'Car Pooling', 'Medium', 'Heap / Priority Queue', false, false, true),
  (295, 'find-median-from-data-stream', 'Find Median From Data Stream', 'Hard', 'Heap / Priority Queue', true, true, true),
  (1383, 'maximum-performance-of-a-team', 'Maximum Performance of a Team', 'Hard', 'Heap / Priority Queue', false, false, false),
  (502, 'ipo', 'IPO', 'Hard', 'Heap / Priority Queue', false, false, true),
  (78, 'subsets', 'Subsets', 'Medium', 'Backtracking', false, true, true),
  (39, 'combination-sum', 'Combination Sum', 'Medium', 'Backtracking', true, true, true),
  (77, 'combinations', 'Combinations', 'Medium', 'Backtracking', false, false, true),
  (46, 'permutations', 'Permutations', 'Medium', 'Backtracking', false, true, true),
  (90, 'subsets-ii', 'Subsets II', 'Medium', 'Backtracking', false, true, true),
  (40, 'combination-sum-ii', 'Combination Sum II', 'Medium', 'Backtracking', false, true, true),
  (47, 'permutations-ii', 'Permutations II', 'Medium', 'Backtracking', false, false, true),
  (79, 'word-search', 'Word Search', 'Medium', 'Backtracking', true, true, true),
  (131, 'palindrome-partitioning', 'Palindrome Partitioning', 'Medium', 'Backtracking', false, true, true),
  (93, 'restore-ip-addresses', 'Restore IP Addresses', 'Medium', 'Backtracking', false, false, false),
  (17, 'letter-combinations-of-a-phone-number', 'Letter Combinations of a Phone Number', 'Medium', 'Backtracking', false, true, true),
  (473, 'matchsticks-to-square', 'Matchsticks to Square', 'Medium', 'Backtracking', false, false, true),
  (1849, 'splitting-a-string-into-descending-consecutive-values', 'Splitting a String Into Descending Consecutive Values', 'Medium', 'Backtracking', false, false, false),
  (1980, 'find-unique-binary-string', 'Find Unique Binary String', 'Medium', 'Backtracking', false, false, false),
  (1239, 'maximum-length-of-a-concatenated-string-with-unique-characters', 'Maximum Length of a Concatenated String With Unique Characters', 'Medium', 'Backtracking', false, false, false),
  (698, 'partition-to-k-equal-sum-subsets', 'Partition to K Equal Sum Subsets', 'Medium', 'Backtracking', false, false, true),
  (51, 'n-queens', 'N Queens', 'Hard', 'Backtracking', false, true, true),
  (52, 'n-queens-ii', 'N Queens II', 'Hard', 'Backtracking', false, false, true),
  (463, 'island-perimeter', 'Island Perimeter', 'Easy', 'Graphs', false, false, true),
  (953, 'verifying-an-alien-dictionary', 'Verifying An Alien Dictionary', 'Easy', 'Graphs', false, false, true),
  (200, 'number-of-islands', 'Number of Islands', 'Medium', 'Graphs', true, true, true),
  (133, 'clone-graph', 'Clone Graph', 'Medium', 'Graphs', true, true, true),
  (695, 'max-area-of-island', 'Max Area of Island', 'Medium', 'Graphs', false, true, true),
  (1905, 'count-sub-islands', 'Count Sub Islands', 'Medium', 'Graphs', false, false, false),
  (417, 'pacific-atlantic-water-flow', 'Pacific Atlantic Water Flow', 'Medium', 'Graphs', true, true, true),
  (130, 'surrounded-regions', 'Surrounded Regions', 'Medium', 'Graphs', false, true, true),
  (1466, 'reorder-routes-to-make-all-paths-lead-to-the-city-zero', 'Reorder Routes to Make All Paths Lead to The City Zero', 'Medium', 'Graphs', false, false, false),
  (994, 'rotting-oranges', 'Rotting Oranges', 'Medium', 'Graphs', false, true, true),
  (286, 'walls-and-gates', 'Walls And Gates', 'Medium', 'Graphs', false, true, true),
  (909, 'snakes-and-ladders', 'Snakes And Ladders', 'Medium', 'Graphs', false, false, false),
  (752, 'open-the-lock', 'Open The Lock', 'Medium', 'Graphs', false, false, true),
  (802, 'find-eventual-safe-states', 'Find Eventual Safe States', 'Medium', 'Graphs', false, false, false),
  (207, 'course-schedule', 'Course Schedule', 'Medium', 'Graphs', true, true, true),
  (210, 'course-schedule-ii', 'Course Schedule II', 'Medium', 'Graphs', false, true, true),
  (1462, 'course-schedule-iv', 'Course Schedule IV', 'Medium', 'Graphs', false, false, true),
  (1958, 'check-if-move-is-legal', 'Check if Move Is Legal', 'Medium', 'Graphs', false, false, false),
  (934, 'shortest-bridge', 'Shortest Bridge', 'Medium', 'Graphs', false, false, false),
  (1091, 'shortest-path-in-binary-matrix', 'Shortest Path in Binary Matrix', 'Medium', 'Graphs', false, false, false),
  (684, 'redundant-connection', 'Redundant Connection', 'Medium', 'Graphs', false, true, true),
  (323, 'number-of-connected-components-in-an-undirected-graph', 'Number of Connected Components In An Undirected Graph', 'Medium', 'Graphs', true, true, true),
  (261, 'graph-valid-tree', 'Graph Valid Tree', 'Medium', 'Graphs', true, true, true),
  (721, 'accounts-merge', 'Accounts Merge', 'Medium', 'Graphs', false, false, true),
  (2359, 'find-closest-node-to-given-two-nodes', 'Find Closest Node to Given Two Nodes', 'Medium', 'Graphs', false, false, false),
  (1162, 'as-far-from-land-as-possible', 'As Far from Land as Possible', 'Medium', 'Graphs', false, false, false),
  (1129, 'shortest-path-with-alternating-colors', 'Shortest Path with Alternating Colors', 'Medium', 'Graphs', false, false, false),
  (2477, 'minimum-fuel-cost-to-report-to-the-capital', 'Minimum Fuel Cost to Report to the Capital', 'Medium', 'Graphs', false, false, false),
  (2492, 'minimum-score-of-a-path-between-two-cities', 'Minimum Score of a Path Between Two Cities', 'Medium', 'Graphs', false, false, false),
  (1254, 'number-of-closed-islands', 'Number of Closed Islands', 'Medium', 'Graphs', false, false, false),
  (1020, 'number-of-enclaves', 'Number of Enclaves', 'Medium', 'Graphs', false, false, false),
  (1557, 'minimum-number-of-vertices-to-reach-all-nodes', 'Minimum Number of Vertices to Reach all Nodes', 'Medium', 'Graphs', false, false, false),
  (785, 'is-graph-bipartite', 'Is Graph Bipartite?', 'Medium', 'Graphs', false, false, false),
  (399, 'evaluate-division', 'Evaluate Division', 'Medium', 'Graphs', false, false, true),
  (2101, 'detonate-the-maximum-bombs', 'Detonate the Maximum Bombs', 'Medium', 'Graphs', false, false, false),
  (1857, 'largest-color-value-in-a-directed-graph', 'Largest Color Value in a Directed Graph', 'Hard', 'Graphs', false, false, false),
  (1553, 'minimum-number-of-days-to-eat-n-oranges', 'Minimum Number of Days to Eat N Oranges', 'Hard', 'Graphs', false, false, false),
  (127, 'word-ladder', 'Word Ladder', 'Hard', 'Graphs', false, true, true),
  (1631, 'path-with-minimum-effort', 'Path with Minimum Effort', 'Medium', 'Advanced Graphs', false, false, true),
  (332, 'reconstruct-itinerary', 'Reconstruct Itinerary', 'Hard', 'Advanced Graphs', false, true, true),
  (1584, 'min-cost-to-connect-all-points', 'Min Cost to Connect All Points', 'Medium', 'Advanced Graphs', false, true, true),
  (743, 'network-delay-time', 'Network Delay Time', 'Medium', 'Advanced Graphs', false, true, true),
  (1514, 'path-with-maximum-probability', 'Path with Maximum Probability', 'Medium', 'Advanced Graphs', false, false, false),
  (778, 'swim-in-rising-water', 'Swim In Rising Water', 'Hard', 'Advanced Graphs', false, true, true),
  (269, 'alien-dictionary', 'Alien Dictionary', 'Hard', 'Advanced Graphs', true, true, true),
  (787, 'cheapest-flights-within-k-stops', 'Cheapest Flights Within K Stops', 'Medium', 'Advanced Graphs', false, true, true),
  (2421, 'number-of-good-paths', 'Number of Good Paths', 'Hard', 'Advanced Graphs', false, false, false),
  (1579, 'remove-max-number-of-edges-to-keep-graph-fully-traversable', 'Remove Max Number of Edges to Keep Graph Fully Traversable', 'Hard', 'Advanced Graphs', false, false, false),
  (1489, 'find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree', 'Find Critical and Pseudo Critical Edges in Minimum Spanning Tree', 'Hard', 'Advanced Graphs', false, false, true),
  (70, 'climbing-stairs', 'Climbing Stairs', 'Easy', '1-D Dynamic Programming', true, true, true),
  (746, 'min-cost-climbing-stairs', 'Min Cost Climbing Stairs', 'Easy', '1-D Dynamic Programming', false, true, true),
  (198, 'house-robber', 'House Robber', 'Medium', '1-D Dynamic Programming', true, true, true),
  (213, 'house-robber-ii', 'House Robber II', 'Medium', '1-D Dynamic Programming', true, true, true),
  (5, 'longest-palindromic-substring', 'Longest Palindromic Substring', 'Medium', '1-D Dynamic Programming', true, true, true),
  (647, 'palindromic-substrings', 'Palindromic Substrings', 'Medium', '1-D Dynamic Programming', true, true, true),
  (91, 'decode-ways', 'Decode Ways', 'Medium', '1-D Dynamic Programming', true, true, true),
  (322, 'coin-change', 'Coin Change', 'Medium', '1-D Dynamic Programming', true, true, true),
  (152, 'maximum-product-subarray', 'Maximum Product Subarray', 'Medium', '1-D Dynamic Programming', true, true, true),
  (139, 'word-break', 'Word Break', 'Medium', '1-D Dynamic Programming', true, true, true),
  (300, 'longest-increasing-subsequence', 'Longest Increasing Subsequence', 'Medium', '1-D Dynamic Programming', true, true, true),
  (416, 'partition-equal-subset-sum', 'Partition Equal Subset Sum', 'Medium', '1-D Dynamic Programming', false, true, true),
  (120, 'triangle', 'Triangle', 'Medium', '1-D Dynamic Programming', false, false, false),
  (740, 'delete-and-earn', 'Delete And Earn', 'Medium', '1-D Dynamic Programming', false, false, false),
  (256, 'paint-house', 'Paint House', 'Medium', '1-D Dynamic Programming', false, false, false),
  (377, 'combination-sum-iv', 'Combination Sum IV', 'Medium', '1-D Dynamic Programming', false, false, true),
  (279, 'perfect-squares', 'Perfect Squares', 'Medium', '1-D Dynamic Programming', false, false, true),
  (2369, 'check-if-there-is-a-valid-partition-for-the-array', 'Check if There is a Valid Partition For The Array', 'Medium', '1-D Dynamic Programming', false, false, false),
  (1856, 'maximum-subarray-min-product', 'Maximum Subarray Min Product', 'Medium', '1-D Dynamic Programming', false, false, false),
  (983, 'minimum-cost-for-tickets', 'Minimum Cost For Tickets', 'Medium', '1-D Dynamic Programming', false, false, false),
  (343, 'integer-break', 'Integer Break', 'Medium', '1-D Dynamic Programming', false, false, true),
  (673, 'number-of-longest-increasing-subsequence', 'Number of Longest Increasing Subsequence', 'Medium', '1-D Dynamic Programming', false, false, false),
  (691, 'stickers-to-spell-word', 'Stickers to Spell Word', 'Hard', '1-D Dynamic Programming', false, false, false),
  (1137, 'n-th-tribonacci-number', 'N-th Tribonacci Number', 'Easy', '1-D Dynamic Programming', false, false, true),
  (1035, 'uncrossed-lines', 'Uncrossed Lines', 'Medium', '1-D Dynamic Programming', false, false, false),
  (2140, 'solving-questions-with-brainpower', 'Solving Questions With Brainpower', 'Medium', '1-D Dynamic Programming', false, false, false),
  (2466, 'count-ways-to-build-good-strings', 'Count Ways to Build Good Strings', 'Medium', '1-D Dynamic Programming', false, false, false),
  (837, 'new-21-game', 'New 21 Game', 'Medium', '1-D Dynamic Programming', false, false, false),
  (1626, 'best-team-with-no-conflicts', 'Best Team with no Conflicts', 'Medium', '1-D Dynamic Programming', false, false, false),
  (1406, 'stone-game-iii', 'Stone Game III', 'Hard', '1-D Dynamic Programming', false, false, true),
  (472, 'concatenated-words', 'Concatenated Words', 'Hard', '1-D Dynamic Programming', false, false, false),
  (1799, 'maximize-score-after-n-operations', 'Maximize Score after N Operations', 'Hard', '1-D Dynamic Programming', false, false, false),
  (1964, 'find-the-longest-valid-obstacle-course-at-each-position', 'Find the Longest Valid Obstacle Course at Each Position', 'Hard', '1-D Dynamic Programming', false, false, false),
  (1359, 'count-all-valid-pickup-and-delivery-options', 'Count all Valid Pickup and Delivery Options', 'Hard', '1-D Dynamic Programming', false, false, false),
  (62, 'unique-paths', 'Unique Paths', 'Medium', '2-D Dynamic Programming', true, true, true),
  (63, 'unique-paths-ii', 'Unique Paths II', 'Medium', '2-D Dynamic Programming', false, false, true),
  (1143, 'longest-common-subsequence', 'Longest Common Subsequence', 'Medium', '2-D Dynamic Programming', true, true, true),
  (516, 'longest-palindromic-subsequence', 'Longest Palindromic Subsequence', 'Medium', '2-D Dynamic Programming', false, false, false),
  (1049, 'last-stone-weight-ii', 'Last Stone Weight II', 'Medium', '2-D Dynamic Programming', false, false, true),
  (309, 'best-time-to-buy-and-sell-stock-with-cooldown', 'Best Time to Buy And Sell Stock With Cooldown', 'Medium', '2-D Dynamic Programming', false, true, true),
  (518, 'coin-change-ii', 'Coin Change II', 'Medium', '2-D Dynamic Programming', false, true, true),
  (494, 'target-sum', 'Target Sum', 'Medium', '2-D Dynamic Programming', false, true, true),
  (97, 'interleaving-string', 'Interleaving String', 'Medium', '2-D Dynamic Programming', false, true, true),
  (877, 'stone-game', 'Stone Game', 'Medium', '2-D Dynamic Programming', false, false, true),
  (64, 'minimum-path-sum', 'Minimum Path Sum', 'Medium', '2-D Dynamic Programming', false, false, true),
  (329, 'longest-increasing-path-in-a-matrix', 'Longest Increasing Path In a Matrix', 'Hard', '2-D Dynamic Programming', false, true, true),
  (221, 'maximal-square', 'Maximal Square', 'Medium', '2-D Dynamic Programming', false, false, false),
  (474, 'ones-and-zeroes', 'Ones and Zeroes', 'Medium', '2-D Dynamic Programming', false, false, false),
  (5782, 'maximum-alternating-subsequence-sum', 'Maximum Alternating Subsequence Sum', 'Medium', '2-D Dynamic Programming', false, false, false),
  (115, 'distinct-subsequences', 'Distinct Subsequences', 'Hard', '2-D Dynamic Programming', false, true, true),
  (72, 'edit-distance', 'Edit Distance', 'Medium', '2-D Dynamic Programming', false, true, true),
  (1220, 'count-vowels-permutation', 'Count Vowels Permutation', 'Hard', '2-D Dynamic Programming', false, false, false),
  (312, 'burst-balloons', 'Burst Balloons', 'Hard', '2-D Dynamic Programming', false, true, true),
  (1866, 'number-of-ways-to-rearrange-sticks-with-k-sticks-visible', 'Number of Ways to Rearrange Sticks With K Sticks Visible', 'Hard', '2-D Dynamic Programming', false, false, false),
  (10, 'regular-expression-matching', 'Regular Expression Matching', 'Hard', '2-D Dynamic Programming', false, true, true),
  (1140, 'stone-game-ii', 'Stone Game II', 'Medium', '2-D Dynamic Programming', false, false, true),
  (926, 'flip-string-to-monotone-increasing', 'Flip String to Monotone Increasing', 'Medium', '2-D Dynamic Programming', false, false, false),
  (2218, 'maximum-value-of-k-coins-from-piles', 'Maximum Value of K Coins from Piles', 'Hard', '2-D Dynamic Programming', false, false, false),
  (920, 'number-of-music-playlists', 'Number of Music Playlists', 'Hard', '2-D Dynamic Programming', false, false, false),
  (1639, 'number-of-ways-to-form-a-target-string-given-a-dictionary', 'Number of Ways to Form a Target String Given a Dictionary', 'Hard', '2-D Dynamic Programming', false, false, false),
  (879, 'profitable-schemes', 'Profitable Schemes', 'Hard', '2-D Dynamic Programming', false, false, false),
  (1547, 'minimum-cost-to-cut-a-stick', 'Minimum Cost to Cut a Stick', 'Hard', '2-D Dynamic Programming', false, false, false),
  (53, 'maximum-subarray', 'Maximum Subarray', 'Medium', 'Greedy', true, true, true),
  (918, 'maximum-sum-circular-subarray', 'Maximum Sum Circular Subarray', 'Medium', 'Greedy', false, false, true),
  (978, 'longest-turbulent-subarray', 'Longest Turbulent Subarray', 'Medium', 'Greedy', false, false, true),
  (55, 'jump-game', 'Jump Game', 'Medium', 'Greedy', true, true, true),
  (45, 'jump-game-ii', 'Jump Game II', 'Medium', 'Greedy', false, true, true),
  (1871, 'jump-game-vii', 'Jump Game VII', 'Medium', 'Greedy', false, false, true),
  (134, 'gas-station', 'Gas Station', 'Medium', 'Greedy', false, true, true),
  (846, 'hand-of-straights', 'Hand of Straights', 'Medium', 'Greedy', false, true, true),
  (2439, 'minimize-maximum-of-array', 'Minimize Maximum of Array', 'Medium', 'Greedy', false, false, false),
  (649, 'dota2-senate', 'Dota2 Senate', 'Medium', 'Greedy', false, false, true),
  (1423, 'maximum-points-you-can-obtain-from-cards', 'Maximum Points You Can Obtain From Cards', 'Medium', 'Greedy', false, false, false),
  (1899, 'merge-triplets-to-form-target-triplet', 'Merge Triplets to Form Target Triplet', 'Medium', 'Greedy', false, true, true),
  (763, 'partition-labels', 'Partition Labels', 'Medium', 'Greedy', false, true, true),
  (678, 'valid-parenthesis-string', 'Valid Parenthesis String', 'Medium', 'Greedy', false, true, true),
  (1921, 'eliminate-maximum-number-of-monsters', 'Eliminate Maximum Number of Monsters', 'Medium', 'Greedy', false, false, false),
  (1029, 'two-city-scheduling', 'Two City Scheduling', 'Medium', 'Greedy', false, false, false),
  (646, 'maximum-length-of-pair-chain', 'Maximum Length of Pair Chain', 'Medium', 'Greedy', false, false, false),
  (1647, 'minimum-deletions-to-make-character-frequencies-unique', 'Minimum Deletions to Make Character Frequencies Unique', 'Medium', 'Greedy', false, false, false),
  (135, 'candy', 'Candy', 'Hard', 'Greedy', false, false, true),
  (57, 'insert-interval', 'Insert Interval', 'Medium', 'Intervals', true, true, true),
  (56, 'merge-intervals', 'Merge Intervals', 'Medium', 'Intervals', true, true, true),
  (435, 'non-overlapping-intervals', 'Non Overlapping Intervals', 'Medium', 'Intervals', true, true, true),
  (252, 'meeting-rooms', 'Meeting Rooms', 'Easy', 'Intervals', true, true, true),
  (253, 'meeting-rooms-ii', 'Meeting Rooms II', 'Medium', 'Intervals', true, true, true),
  (1288, 'remove-covered-intervals', 'Remove Covered Intervals', 'Medium', 'Intervals', false, false, false),
  (1851, 'minimum-interval-to-include-each-query', 'Minimum Interval to Include Each Query', 'Hard', 'Intervals', false, true, true),
  (352, 'data-stream-as-disjoint-intervals', 'Data Stream as Disjoint Intervals', 'Hard', 'Intervals', false, false, false),
  (168, 'excel-sheet-column-title', 'Excel Sheet Column Title', 'Easy', 'Math & Geometry', false, false, true),
  (1071, 'greatest-common-divisor-of-strings', 'Greatest Common Divisor of Strings', 'Easy', 'Math & Geometry', false, false, true),
  (1523, 'count-odd-numbers-in-an-interval-range', 'Count Odd Numbers in an Interval Range', 'Easy', 'Math & Geometry', false, false, false),
  (1572, 'matrix-diagonal-sum', 'Matrix Diagonal Sum', 'Easy', 'Math & Geometry', false, false, false),
  (149, 'max-points-on-a-line', 'Maximum Points on a Line', 'Hard', 'Math & Geometry', false, false, false),
  (48, 'rotate-image', 'Rotate Image', 'Medium', 'Math & Geometry', true, true, true),
  (54, 'spiral-matrix', 'Spiral Matrix', 'Medium', 'Math & Geometry', true, true, true),
  (59, 'spiral-matrix-ii', 'Spiral Matrix II ', 'Medium', 'Math & Geometry', false, false, false),
  (73, 'set-matrix-zeroes', 'Set Matrix Zeroes', 'Medium', 'Math & Geometry', true, true, true),
  (202, 'happy-number', 'Happy Number', 'Easy', 'Math & Geometry', false, true, true),
  (66, 'plus-one', 'Plus One', 'Easy', 'Math & Geometry', false, true, true),
  (9, 'palindrome-number', 'Palindrome Number', 'Easy', 'Math & Geometry', false, false, false),
  (263, 'ugly-number', 'Ugly Number', 'Easy', 'Math & Geometry', false, false, false),
  (1260, 'shift-2d-grid', 'Shift 2D Grid', 'Easy', 'Math & Geometry', false, false, false),
  (13, 'roman-to-integer', 'Roman to Integer', 'Easy', 'Math & Geometry', false, false, true),
  (12, 'integer-to-roman', 'Integer to Roman', 'Medium', 'Math & Geometry', false, false, false),
  (50, 'powx-n', 'Pow(x, n)', 'Medium', 'Math & Geometry', false, true, true),
  (43, 'multiply-strings', 'Multiply Strings', 'Medium', 'Math & Geometry', false, true, true),
  (2013, 'detect-squares', 'Detect Squares', 'Medium', 'Math & Geometry', false, true, true),
  (1041, 'robot-bounded-in-circle', 'Robot Bounded In Circle', 'Medium', 'Math & Geometry', false, false, false),
  (6, 'zigzag-conversion', 'Zigzag Conversion', 'Medium', 'Math & Geometry', false, false, false),
  (2028, 'find-missing-observations', 'Find Missing Observations', 'Medium', 'Math & Geometry', false, false, false),
  (136, 'single-number', 'Single Number', 'Easy', 'Bit Manipulation', false, true, true),
  (191, 'number-of-1-bits', 'Number of 1 Bits', 'Easy', 'Bit Manipulation', true, true, true),
  (338, 'counting-bits', 'Counting Bits', 'Easy', 'Bit Manipulation', true, true, true),
  (190, 'reverse-bits', 'Reverse Bits', 'Easy', 'Bit Manipulation', true, true, true),
  (268, 'missing-number', 'Missing Number', 'Easy', 'Bit Manipulation', true, true, true),
  (1470, 'shuffle-the-array', 'Shuffle the Array', 'Easy', 'Bit Manipulation', false, false, false),
  (989, 'add-to-array-form-of-integer', 'Add to Array-Form of Integer', 'Easy', 'Bit Manipulation', false, false, false),
  (371, 'sum-of-two-integers', 'Sum of Two Integers', 'Medium', 'Bit Manipulation', true, true, true),
  (7, 'reverse-integer', 'Reverse Integer', 'Medium', 'Bit Manipulation', false, true, true),
  (67, 'add-binary', 'Add Binary', 'Easy', 'Bit Manipulation', false, false, true),
  (2667, 'create-hello-world-function', 'Create Hello World Function', 'Easy', 'JavaScript', false, false, false),
  (2620, 'counter', 'Counter', 'Easy', 'JavaScript', false, false, false),
  (2665, 'counter-ii', 'Counter II', 'Easy', 'JavaScript', false, false, false),
  (2635, 'apply-transform-over-each-element-in-array', 'Apply Transform over each Element in Array', 'Easy', 'JavaScript', false, false, false),
  (2634, 'filter-elements-from-array', 'Filter Elements from Array', 'Easy', 'JavaScript', false, false, false),
  (2626, 'array-reduce-transformation', 'Array Reduce Transformation', 'Easy', 'JavaScript', false, false, false),
  (2629, 'function-composition', 'Function Composition', 'Easy', 'JavaScript', false, false, false),
  (2666, 'allow-one-function-call', 'Allow One Function Call', 'Easy', 'JavaScript', false, false, false),
  (2623, 'memoize', 'Memoize', 'Medium', 'JavaScript', false, false, false),
  (2632, 'curry', 'Curry', 'Medium', 'JavaScript', false, false, false),
  (2621, 'sleep', 'Sleep', 'Easy', 'JavaScript', false, false, false),
  (2637, 'promise-time-limit', 'Promise Time Limit', 'Easy', 'JavaScript', false, false, false),
  (2636, 'promise-pool', 'Promise Pool', 'Medium', 'JavaScript', false, false, false),
  (2622, 'cache-with-time-limit', 'Cache With Time Limit', 'Medium', 'JavaScript', false, false, false),
  (2627, 'debounce', 'Debounce', 'Medium', 'JavaScript', false, false, false),
  (2676, 'throttle', 'Throttle', 'Medium', 'JavaScript', false, false, false),
  (2628, 'json-deep-equal', 'JSON Deep Equal', 'Medium', 'JavaScript', false, false, false),
  (2633, 'convert-object-to-json-string', 'Convert Object to JSON String', 'Medium', 'JavaScript', false, false, false),
  (2675, 'array-of-objects-to-matrix', 'Array of Objects to Matrix', 'Medium', 'JavaScript', false, false, false),
  (2700, 'differences-between-two-objects', 'Difference Between Two Objects', 'Medium', 'JavaScript', false, false, false),
  (2677, 'chunk-array', 'Chunk Array', 'Easy', 'JavaScript', false, false, false),
  (2625, 'flatten-deeply-nested-array', 'Flatten Deeply Nested Array', 'Medium', 'JavaScript', false, false, false),
  (2619, 'array-prototype-last', 'Array Prototype Last', 'Easy', 'JavaScript', false, false, false),
  (2631, 'group-by', 'Group By', 'Medium', 'JavaScript', false, false, false),
  (2618, 'check-if-object-instance-of-class', 'Check if Object Instance of Class', 'Medium', 'JavaScript', false, false, false),
  (2693, 'call-function-with-custom-context', 'Call Function with Custom Context', 'Medium', 'JavaScript', false, false, false),
  (2694, 'event-emitter', 'Event Emitter', 'Medium', 'JavaScript', false, false, false),
  (2695, 'array-wrapper', 'Array Wrapper', 'Easy', 'JavaScript', false, false, false),
  (2648, 'generate-fibonacci-sequence', 'Generate Fibonacci Sequence', 'Easy', 'JavaScript', false, false, false),
  (2649, 'nested-array-generator', 'Nested Array Generator', 'Medium', 'JavaScript', false, false, false),
  (229, 'majority-element-ii', 'Majority Element II', 'Medium', 'Arrays & Hashing', false, false, true),
  (232, 'implement-queue-using-stacks', 'Implement Queue using Stacks', 'Easy', 'Stack', false, false, true),
  (1095, 'find-in-mountain-array', 'Find in Mountain Array', 'Hard', 'Binary Search', false, false, true),
  (1325, 'delete-leaves-with-a-given-value', 'Delete Leaves With a Given Value', 'Medium', 'Trees', false, false, true),
  (1863, 'sum-of-all-subset-xor-totals', 'Sum of All Subset XOR Totals', 'Easy', 'Backtracking', false, false, true),
  (140, 'word-break-ii', 'Word Break II', 'Hard', 'Backtracking', false, false, true),
  (997, 'find-the-town-judge', 'Find the Town Judge', 'Easy', 'Graphs', false, false, true),
  (310, 'minimum-height-trees', 'Minimum Height Trees', 'Medium', 'Graphs', false, false, true),
  (2392, 'build-a-matrix-with-conditions', 'Build a Matrix With Conditions', 'Hard', 'Advanced Graphs', false, false, true),
  (2709, 'greatest-common-divisor-traversal', 'Greatest Common Divisor Traversal', 'Hard', 'Advanced Graphs', false, false, true),
  (860, 'lemonade-change', 'Lemonade Change', 'Easy', 'Greedy', false, false, true),
  (2402, 'meeting-rooms-iii', 'Meeting Rooms III', 'Hard', 'Intervals', false, false, true),
  (2807, 'insert-greatest-common-divisors-in-linked-list', 'Insert Greatest Common Divisors in Linked List', 'Medium', 'Math & Geometry', false, false, true),
  (867, 'transpose-matrix', 'Transpose Matrix', 'Easy', 'Math & Geometry', false, false, true),
  (201, 'bitwise-and-of-numbers-range', 'Bitwise AND of Numbers Range', 'Medium', 'Bit Manipulation', false, false, true),
  (3133, 'minimum-array-end', 'Minimum Array End', 'Medium', 'Bit Manipulation', false, false, true)
on conflict (id) do update set
  slug=excluded.slug, title=excluded.title, difficulty=excluded.difficulty,
  category=excluded.category, blind75=excluded.blind75, neetcode150=excluded.neetcode150, neetcode250=excluded.neetcode250;
