export type Diff = "Easy" | "Medium" | "Hard";
export type Problem = { name: string; slug: string; diff: Diff; done: boolean; optimal: boolean; blind75: boolean; neetcode150: boolean; neetcode250: boolean };
export type ProblemList = "blind75" | "neetcode150" | "neetcode250" | "all";
export type Friend = { id: string; name: string; initials: string; username: string; color: string };
export type Solution = { lang: string; runtimeMs: number; runtimePct: number; optimal: boolean; code: string };
export type Month = { year: number; month: number };
export type Person = { name: string; initials: string; color: string };
export type Member = {
  name: string;
  initials: string;
  color: string;
  solved: number;
  solvedByList: Record<ProblemList, number>;
  byDiff: { easy: number; medium: number; hard: number };
  streak?: number;
  username?: string;
};
export type RecentItem = { n: number; slug: string; name: string; diff: string; who: Person[]; at: string };
export type CalendarProblem = { slug: string; name: string; diff: string };
export type DifficultyTotal = { label: string; count: number };
export type Category = { title: string; items: Problem[] };
export type ProblemRef = { name: string; slug: string; diff: string };
